config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get  :search, on: :collection
    resource :comment, only: :create, controller: 'posts/comments'
    resource :vote, only: :create, controller: 'posts/votes'
  end

  mount Sidekiq::Web => '/sidekiq'

  root to: 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_closure_tree order: 'created_at DESC'

  belongs_to :owner, foreign_key: 'owner_id', class_name: 'User'
  belongs_to :post

  delegate :name_or_email, to: :owner, prefix: true

  validates :body, :owner, :post, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  include PgSearch

  friendly_id :title, use: [:slugged, :finders]
  pg_search_scope :search_by_title, :against => :title

  belongs_to :owner, foreign_key: 'owner_id', class_name: 'User'
  has_many   :comments
  has_many   :votes

  validates :title, :url, presence: true

  delegate :name_or_email, to: :owner, prefix: true

  scope :voted_for_in_last, -> (time_ago) { joins(:votes).where('votes.created_at > ?', time_ago) }

  def humanized_rating
    (rating * 100).round
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts,    foreign_key: 'owner_id'
  has_many :comments, foreign_key: 'owner_id'
  has_many :votes

  def name_or_email
    name.presence || email
  end

  def vote_for(post, direction)
    votes.where(post: post).first_or_create(direction: direction)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  scope :positive, ->{ where(direction: 'up') }
  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  def create
    comment = Comment.create!(comment_params.merge({post_id: params[:post_id], owner: current_user}))
    redirect_to :back
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end
end

app/controllers/posts/votes_controller.rb
class Posts::VotesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    render json: { success: (current_user.vote_for(post, params[:vote]) if post.present?) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('rating DESC').page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  # Please, think of this as a stub method.
  # There's no free account for elasticsearch on Heroku
  def search
    @posts = Post.search_by_title(params[:criterium]).page(params[:page]).per(10)
  end

  private
    def post_params
      params.require(:post).permit(:url, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts/comments_helper.rb
module Posts::CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render('posts/comments/comment', comment: comment, nested_comments: nested_comments)
    end.join.html_safe
  end
end

app/helpers/posts/votes_helper.rb
module Posts::VotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Rattle
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    = render 'shared/navigation'

    .container
      .row
        .col-md-8
          = yield
        = render 'shared/sidebar'
      %hr/
      %footer
        .row
          .col-lg-12
            %p Copyright © Rattle 2015

app/views/posts/_item.html.haml
.post-wrapper.row
  .col-md-1
    .voting
      = button_to post_vote_path(post), { params: { vote: :up }, remote: true, class: 'btn btn-default btn-xs btn-block'} do
        %i.glyphicon.glyphicon-arrow-up
      .rating
        = post.humanized_rating
      = button_to post_vote_path(post), { params: { vote: :down }, remote: true, class: 'btn btn-default btn-xs btn-block'} do
        %i.glyphicon.glyphicon-arrow-down
  .col-md-11
    .post
      %h2
        = link_to post.title, post.url
      %p.lead
        by
        = post.owner_name_or_email
      %p
        %span.glyphicon.glyphicon-time
        Posted on #{post.created_at.strftime("%A, %B %d, %Y at %H:%M")}
        = link_to "Comments (#{post.comments.count}) >>", post_path(post)
%hr/

app/views/posts/comments/_collection.html.haml
= comments_tree_for comments

app/views/posts/comments/_comment.html.haml
.well
  %p.text-muted
    Added by
    %strong= comment.owner_name_or_email
    on
    \#{l(comment.created_at, format: '%B, %d %Y %H:%M:%S')}
  %blockquote
    %p= comment.body
    .comment-form.hidden
      = render 'posts/comments/form', comment: comment.children.build(post_id: comment.post_id)
    =link_to 'Reply', '#', class: 'btn btn-default reply'
    = render 'posts/comments/collection', comments: nested_comments

app/views/posts/comments/_form.html.haml
= form_for(comment, url: post_comment_path(comment.post_id)) do |f|
  - if comment.errors.any?
    #error_explanation
      %h2
        = pluralize(comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - comment.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', required: true
    = f.text_field :parent_id, hidden: true
  = f.submit class: 'btn btn-primary'

app/views/posts/index.html.haml
.col-md-12
  %h1.page-header
    Top posts
    %small from all subrattles
  - @posts.each do |post|
    = render 'posts/item', post: post
  = paginate @posts

app/views/posts/new.html.haml
%h3 New post
= bootstrap_form_for @post do |f|
  = f.text_field :title
  = f.text_field :url
  = f.submit

app/views/posts/search.html.haml
.col-md-8
  %h1.page-header
    "#{params[:criterium]}"
    %small search results
  - @posts.each do |post|
    %h2
      = link_to post.title, post.url
    %p.lead
      by
      = post.owner_name_or_email
    %p
      %span.glyphicon.glyphicon-time
      Posted on August 28, 2013 at 10:00 PM
    %hr/

  = paginate @posts
x

app/views/posts/show.html.haml
.col-md-12
  = render 'posts/item', post: @post
  .comments
    = render 'posts/comments/collection', comments: @post.comments.hash_tree
    = render 'posts/comments/form', comment: @post.comments.build

app/views/shared/_navigation.html.haml
/ Navigation
%nav.navbar.navbar-inverse{role: "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Rattle', root_path, class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user.present?
          %li
            %p.navbar-text
              Looged in as #{current_user.name || current_user.email}
          %li
            = link_to 'Sign out', destroy_user_session_path
        - else
          %li
            = link_to 'Sign up', new_user_registration_path
          %li
            = link_to 'Sign in', new_user_session_path

    / /.navbar-collapse
  / /.container

app/views/shared/_sidebar.html.haml
.col-md-4
  .well
    %h4 Blog Search
    = bootstrap_form_tag url: search_posts_path, method: :get do |f|
      = f.text_field :criterium, append: f.submit('Find'), hide_label: true
  - if current_user.present?
    .well
      = link_to new_post_path do
        .btn.btn-default.btn-block
          %i.glyphicon.glyphicon-plus
          Create post
  .well
    %h4 Rattle
    %p Just another reddit clone without good search because of Heroku